### ISSUE TITLE
Include `libcublas.so` in `libcublas`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/libcublas-feedstock#1]
> I've seen code that uses `dlopen` / `dlsym` as well as `ctypes` code that expects to use just the `lib*.so` as opposed to the versioned shared library at runtime. Not a blocker, but have we considered having the `libcublas.so` symlink in this package as opposed to the `dev` package? I know that the `SONAME` points to `libcublas.so.12`, but there's definitely code out there that will end up requiring `libcublas-dev` at runtime because of this.
>
> Definitely not a blocker for getting this in though!

_Originally posted by @kkraus14 in https://github.com/conda-forge/staged-recipes/pull/21901#discussion_r1154924908_

**Comment by jakirkham** [comment]
cc @adibbley @bdice @robertmaynard

**Comment by jakirkham** [comment]
> We've been reworking RAPIDS code to use the proper SONAME form, like `libcublas.so.12`, anywhere that we've seen that. I could see an argument that it's a bug to rely on `dlopen`ing the unversioned form? That said, I don't have a reference for how we've packaged this in other CUDA Toolkit deployments to know if this approach is "normal" or not. I agree that we shouldn't treat this as a blocker, and I'd be happy to discuss further if users run into specific issues.

Originally posted by @bdice in https://github.com/conda-forge/staged-recipes/pull/21901#discussion_r1154930462

**Comment by jakirkham** [comment]
Think this has been resolved by teaching the compilation tooling to look in the right place. If we are still missing some combination of flags, let's discuss that in a new issue with a minimal reproducer

**Comment by kkraus14** [comment]
> Think this has been resolved by teaching the compilation tooling to look in the right place.

**Comment by jakirkham** [comment]
After a fair bit of discussion, the conclusion we came to was SOVERSIONs should be included in libraries that are being `dlopen`ed

We went through making similar changes in RAPIDS relating to `libcufile` where this was an issue. Here's some related PRs that implemented that:
* https://github.com/rapidsai/kvikio/pull/203
* https://github.com/rapidsai/cudf/pull/13210
* https://github.com/rapidsai/cucim/pull/548

**Comment by kkraus14** [comment]
I have a strong suspicion we'll see things still dlopen `libcublas.so` and just depend on the `dev` package instead of trying to `dlopen` the versioned binaries, but we can revisit if needed then I guess?

**Comment by jakirkham** [comment]
Yeah we started looking through other Python libraries for this behavior. Generally they seemed to be doing the right thing. That said, there certainly could be more out there
