### ISSUE TITLE
Fix license URL on Anaconda.org

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/libcublas-feedstock#2]
Despite having `license_url` in the recipes and packages, Anaconda.org is using an incorrect link to a broken page.

https://github.com/conda-forge/libcublas-feedstock/blob/7ede7517d0d09d649f582eed3aaa7f0a2bb29997/recipe/meta.yaml#L62

![image](https://user-images.githubusercontent.com/3019665/229248362-eb1a886f-663c-4aeb-8e91-42d1e6687d76.png)

The other links work. Also the packages contain the license file.

We have seen this issue before ( https://github.com/conda-forge/cudatoolkit-feedstock/issues/2 ). This can be fixed by editing the link in the Anaconda.org web UI. Raised an upstream issue ( https://github.com/conda/infrastructure/discussions/739 ) as well since this would ideally be handled automatically

**Comment by leofang** [comment]
Most of NVIDIA product feedstocks have this issue, e.g., https://github.com/conda-forge/cuquantum-feedstock/issues/3.

**Comment by leofang** [comment]
This issue seems to be fixed now!
