### ISSUE TITLE
`libcublas` is not built on ppc64le/aarch64

### ISSUE THREAD

**Issue by leofang** [conda-forge/libcublas-feedstock#5]
I think this is by design of conda-forge (after creating a feedstock, we need to add the package to [this list](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/arch_rebuild.txt) to kick off a rebuild for these platforms). The question is whether we want to do this for all CUDA packages. Let's create an issue to track this need, and discuss it during the sync-up.

btw this is blocking https://github.com/conda-forge/cutensor-feedstock/pull/40.

cc: @jakirkham

**Comment by leofang** [comment]
Sent a PR to kick off the bot: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4306

**Comment by jakirkham** [comment]
Thanks Leo! 🙏

Looks like the bot opened PR ( https://github.com/conda-forge/libcublas-feedstock/pull/6 )

**Comment by leofang** [comment]
Fixed in #6.
